// ESLint configuration for the CleanThis extension.
//
// The shipped code is plain classic scripts — no bundler, no transpilation, no
// modules — so the three groups below differ mainly in which globals exist:
//
//   src/     browser + extension APIs; loaded via importScripts (Chromium) or
//            the manifest's background.scripts array (Firefox), so every file
//            shares one global scope and `self.CleanThis*` is the seam.
//   build.js, tools/, test/   Node, CommonJS.
//
// Style is deliberately not linted here. web-ext lint already covers the
// add-on-specific rules on the built output (`npm run lint:firefox`); this
// config is for the correctness classes that reading alone misses — unused
// bindings, undeclared globals, unreachable code.

"use strict";

const js = require("@eslint/js");
const globals = require("globals");
const { defineConfig, globalIgnores } = require("eslint/config");

// Two house conventions this codebase uses on purpose, encoded once so the
// lint agrees with the code rather than the other way round.
//
//   catch (_)   — "this failure is deliberately ignored"; the block above the
//                 catch says what the fallback is. ~85 sites.
//   let x = null; try { ({ k: x = null } = await store.get(k)); } catch { return; }
//               — the initializer is never read (the catch returns), so
//                 no-useless-assignment flags all 14 sites. It is defensive on
//                 purpose: it pins the type and keeps the function correct if a
//                 later edit stops returning from the catch. Rewriting correct,
//                 deliberately-defensive code to satisfy the rule would make the
//                 file more fragile, so the rule is off rather than the code changed.
const RULES = {
  "no-unused-vars": [
    "error",
    { args: "after-used", caughtErrorsIgnorePattern: "^_", varsIgnorePattern: "^_" },
  ],
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-useless-assignment": "off",
};

module.exports = defineConfig([
  // dist/ is generated by build.js and gitignored; linting it would report
  // every finding twice (once in src/, once in each browser's copy).
  globalIgnores(["dist/", "node_modules/", "web-ext-artifacts/"]),

  {
    files: ["src/**/*.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.webextensions,
        ...globals.serviceworker,
      },
    },
    rules: RULES,
  },

  {
    files: ["build.js", "eslint.config.js", "tools/**/*.js", "test/**/*.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "commonjs",
      globals: {
        ...globals.node,
        // The Playwright harnesses ship arrow functions into the page with
        // page.evaluate(), so browser and extension globals are legitimately
        // in scope inside those callbacks even though the file itself is Node.
        // ESLint sees one flat scope and cannot tell the two apart.
        ...globals.browser,
        ...globals.webextensions,
        ...globals.serviceworker,
      },
    },
    rules: RULES,
  },
]);
